"use client";
import {BrowserRouter,Routes,Route,Navigate,Link} from "react-router-dom";
import {useEffect,useMemo,useState} from "react";
import {FinanceProvider,useFinance} from "./context/FinanceContext";
import AppShell from "./components/AppShell";
import {CashFlowChart,DonutChart} from "./components/Charts";
import {accounts,budgets,holdings,goals,bills,monthly} from "./data/financeData";
import {formatCurrency,percent} from "./utils/formatCurrency";
import {getUsdRate} from "./services/exchangeApi";

const Masked=({value})=>{const {balancesVisible}=useFinance();return balancesVisible?formatCurrency(value):"Rs. ••••••"};
const Stat=({label,value,change,tone="good"})=><article className="stat-card"><div><span>{label}</span><button aria-label={`More about ${label}`}>···</button></div><strong>{value}</strong>{change&&<small className={tone}>{change}</small>}</article>;
const Panel=({title,meta,children,className=""})=><section className={`panel ${className}`}><header><div><h2>{title}</h2>{meta&&<p>{meta}</p>}</div></header>{children}</section>;

function Dashboard(){const {transactions,balancesVisible,setBalancesVisible}=useFinance();const expenses=164800,income=330000;return <AppShell title="Good morning, Muhammad" subtitle="Wednesday, 20 August"><div className="summary-row"><Stat label="Total balance" value={balancesVisible?"Rs. 1,284,650":"Rs. ••••••"} change="↑ 3.4% from July"/><Stat label="Income this month" value="Rs. 330,000" change="Rs. 45,000 freelance income"/><Stat label="Spent this month" value="Rs. 164,800" change="↓ 11.9% from July"/><Stat label="Savings rate" value={`${Math.round((income-expenses)/income*100)}%`} change="5 points above July"/></div><div className="dashboard-grid"><Panel title="Cash flow" meta="Income and expenses · Mar–Aug" className="wide"><CashFlowChart data={monthly}/><div className="net-flow"><span>Net cash flow in August</span><b>+ Rs. 165,200</b></div></Panel><Panel title="Spending by category" meta="August 2026"><DonutChart items={budgets}/></Panel><Panel title="Recent transactions" meta="Latest account activity" className="wide"><TransactionList rows={transactions.slice(0,6)}/><Link className="panel-link" to="/app/transactions">View all transactions →</Link></Panel><Panel title="Upcoming bills" meta="Next 14 days"><div className="bill-list">{bills.slice(0,4).map(b=><div key={b.name}><span className="merchant-icon">{b.name[0]}</span><div><b>{b.name}</b><small>{b.due}</small></div><strong>{formatCurrency(b.amount)}</strong></div>)}</div><Link className="panel-link" to="/app/bills">Manage bills →</Link></Panel><Panel title="Monthly budgets" meta="Rs. 35,031 remaining"><div className="budget-mini">{budgets.slice(0,4).map(b=><div key={b.category}><p><b>{b.category}</b><span>{formatCurrency(b.spent)} of {formatCurrency(b.limit)}</span></p><progress value={b.spent} max={b.limit}/></div>)}</div><Link className="panel-link" to="/app/budgets">Review budget →</Link></Panel><Panel title="Smart insights" meta="Based on your August activity"><div className="insight-list"><article><i>↘</i><p><b>Spending is down 11.9%</b><span>You spent Rs. 22,200 less than in July.</span></p></article><article><i>!</i><p><b>Transport is close to its limit</b><span>Rs. 3,220 remains in this category.</span></p></article><article><i>◎</i><p><b>Your savings rate improved</b><span>It moved from 45% in July to 50% this month.</span></p></article></div></Panel></div><button className="balance-fab" onClick={()=>setBalancesVisible(!balancesVisible)}>{balancesVisible?"Hide":"Show"} balances</button></AppShell>}

function TransactionList({rows,selectable=false,selected=[],toggle}){return <div className="table-wrap"><table><thead><tr>{selectable&&<th><input type="checkbox" aria-label="Select all"/></th>}<th>Transaction</th><th>Date</th><th>Category</th><th>Account</th><th className="right">Amount</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}>{selectable&&<td><input type="checkbox" checked={selected.includes(t.id)} onChange={()=>toggle(t.id)} aria-label={`Select ${t.merchant}`}/></td>}<td><div className="transaction-name"><span className={t.type}>{t.merchant[0]}</span><div><b>{t.merchant}</b><small>{t.note}</small></div></div></td><td>{new Date(t.date).toLocaleDateString("en-PK",{day:"2-digit",month:"short"})}</td><td><span className="category-pill">{t.category}</span></td><td>{t.account}</td><td className={`right amount ${t.amount>0?"positive":""}`}>{t.amount>0?"+":"−"} {formatCurrency(t.amount)}</td></tr>)}</tbody></table></div>}

function Transactions(){const {transactions,setTransactions}=useFinance();const [query,setQuery]=useState("");const [category,setCategory]=useState("All categories");const [sort,setSort]=useState("Newest");const [selected,setSelected]=useState([]);const [modal,setModal]=useState(false);const filtered=useMemo(()=>transactions.filter(t=>(t.merchant+t.note).toLowerCase().includes(query.toLowerCase())&&(category==="All categories"||t.category===category)).sort((a,b)=>sort==="Highest amount"?Math.abs(b.amount)-Math.abs(a.amount):b.date.localeCompare(a.date)),[transactions,query,category,sort]);function add(e){e.preventDefault();const fd=new FormData(e.currentTarget);setTransactions(ts=>[{id:Date.now(),date:fd.get("date"),merchant:fd.get("merchant"),category:fd.get("category"),account:"Meezan Current",amount:-Number(fd.get("amount")),type:"expense",note:fd.get("note")||"Added manually"},...ts]);setModal(false)}return <AppShell title="Transactions" subtitle="Review and organise account activity" action={<button className="primary-action" onClick={()=>setModal(true)}>＋ Add transaction</button>}><div className="toolbar"><label className="table-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search transactions"/></label><select value={category} onChange={e=>setCategory(e.target.value)}>{["All categories",...new Set(transactions.map(t=>t.category))].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option>Newest</option><option>Highest amount</option></select><button>↥ Export CSV</button></div><Panel title={`${filtered.length} transactions`} meta="August 2026"><TransactionList rows={filtered} selectable selected={selected} toggle={id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}/><div className="pagination"><span>Showing 1–{filtered.length} of {filtered.length}</span><div><button disabled>←</button><button className="active">1</button><button disabled>→</button></div></div></Panel>{modal&&<Modal title="Add transaction" close={()=>setModal(false)}><form className="entry-form" onSubmit={add}><label>Merchant or description<input name="merchant" required placeholder="e.g. Green Mart"/></label><div><label>Amount (PKR)<input name="amount" type="number" min="1" required/></label><label>Date<input name="date" type="date" defaultValue="2026-08-20" required/></label></div><label>Category<select name="category">{["Groceries","Transport","Utilities","Dining","Shopping","Health","Education"].map(x=><option key={x}>{x}</option>)}</select></label><label>Note<input name="note" placeholder="Optional note"/></label><div className="form-actions"><button type="button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-action">Add transaction</button></div></form></Modal>}</AppShell>}

function Budgets(){const total=budgets.reduce((s,b)=>s+b.limit,0),spent=budgets.reduce((s,b)=>s+b.spent,0);return <AppShell title="Monthly budget" subtitle="August 2026" action={<button className="primary-action">＋ Add category</button>}><div className="summary-row three"><Stat label="Planned spending" value={formatCurrency(total)}/><Stat label="Spent so far" value={formatCurrency(spent)} change={`${percent(spent,total)}% of plan`}/><Stat label="Remaining" value={formatCurrency(total-spent)} change="11 days left this month"/></div><Panel title="Category budgets" meta="Planned compared with actual spending"><div className="budget-cards">{budgets.map(b=>{const p=percent(b.spent,b.limit);return <article key={b.category}><div><span className="category-dot" style={{background:b.color}}/><div><b>{b.category}</b><small>{p>=100?"Over budget":p>=80?"Near limit":"On track"}</small></div><button>···</button></div><strong>{formatCurrency(b.spent)} <small>of {formatCurrency(b.limit)}</small></strong><progress className={p>=80?"warning":""} value={b.spent} max={b.limit}/><p><span>{formatCurrency(Math.max(0,b.limit-b.spent))} remaining</span><b>{p}%</b></p></article>})}</div></Panel></AppShell>}

function Investments(){const invested=holdings.reduce((s,h)=>s+h.qty*h.avg,0),value=holdings.reduce((s,h)=>s+h.qty*h.price,0);const [rate,setRate]=useState({state:"loading"});useEffect(()=>{const c=new AbortController();getUsdRate(c.signal).then(data=>setRate({state:"ready",...data})).catch(()=>setRate({state:"error"}));return()=>c.abort()},[]);return <AppShell title="Investments" subtitle="Portfolio overview" action={<button className="primary-action">＋ Add holding</button>}><div className="summary-row"><Stat label="Portfolio value" value={formatCurrency(value)} change={`↑ ${formatCurrency(value-invested)} total gain`}/><Stat label="Amount invested" value={formatCurrency(invested)}/><Stat label="Total return" value={`+${((value-invested)/invested*100).toFixed(1)}%`} change="Illustrative market data"/><Stat label="USD reference rate" value={rate.state==="ready"?`Rs. ${rate.rate.toFixed(2)}`:rate.state==="loading"?"Loading…":"Unavailable"} change={rate.state==="ready"?`${rate.source} · ${rate.date}`:"Using portfolio data only"} tone={rate.state==="error"?"warn":"good"}/></div><div className="dashboard-grid"><Panel title="Portfolio performance" meta="Illustrative value · Mar–Aug" className="wide"><div className="portfolio-chart"><div className="line-shape"><i/><i/><i/><i/><i/><i/></div><div className="chart-axis"><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span></div></div></Panel><Panel title="Allocation" meta="By current value"><DonutChart items={holdings.map((h,i)=>({category:h.symbol,spent:h.qty*h.price,color:["#176b4d","#3d6f91","#a86e2e","#735f91"][i]}))}/></Panel></div><Panel title="Holdings" meta={`${holdings.length} assets · prices are illustrative`}><div className="table-wrap"><table><thead><tr><th>Asset</th><th>Quantity</th><th>Average cost</th><th>Current price</th><th>Market value</th><th className="right">Gain / loss</th></tr></thead><tbody>{holdings.map(h=>{const gain=h.qty*(h.price-h.avg);return <tr key={h.symbol}><td><div className="asset"><span>{h.symbol.slice(0,2)}</span><div><b>{h.asset}</b><small>{h.symbol}</small></div></div></td><td>{h.qty}</td><td>{formatCurrency(h.avg)}</td><td>{formatCurrency(h.price)}</td><td>{formatCurrency(h.qty*h.price)}</td><td className="right positive">+ {formatCurrency(gain)}<small> {((h.price/h.avg-1)*100).toFixed(1)}%</small></td></tr>})}</tbody></table></div></Panel><p className="disclaimer">Investment values in this portfolio demo are illustrative and are not financial advice or live market quotes.</p></AppShell>}

function Goals(){return <AppShell title="Savings & goals" subtitle="Build toward what matters" action={<button className="primary-action">＋ New goal</button>}><div className="summary-row three"><Stat label="Saved across goals" value={formatCurrency(goals.reduce((s,g)=>s+g.saved,0))} change="Rs. 94,000 contributed this month"/><Stat label="Total targets" value={formatCurrency(goals.reduce((s,g)=>s+g.target,0))}/><Stat label="Monthly contributions" value={formatCurrency(goals.reduce((s,g)=>s+g.monthly,0))} change="Scheduled for 1 September"/></div><div className="goal-grid">{goals.map((g,i)=><article className="goal-card" key={g.name}><div className={`goal-icon g${i}`}>{["⌂","▣","✈"][i]}</div><button>···</button><h2>{g.name}</h2><p><span>{formatCurrency(g.saved)}</span> of {formatCurrency(g.target)}</p><progress value={g.saved} max={g.target}/><div><span><small>Progress</small><b>{percent(g.saved,g.target)}%</b></span><span><small>Target date</small><b>{g.date}</b></span><span><small>Monthly</small><b>{formatCurrency(g.monthly)}</b></span></div><button className="secondary-action">Add contribution</button></article>)}</div></AppShell>}

function Bills(){return <AppShell title="Bills & recurring payments" subtitle="Keep upcoming commitments in view" action={<button className="primary-action">＋ Add bill</button>}><div className="summary-row three"><Stat label="Due in next 7 days" value="Rs. 7,649" change="2 payments" tone="warn"/><Stat label="Monthly recurring" value="Rs. 92,669" change="5 active payments"/><Stat label="Paid this month" value="Rs. 88,719" change="All paid on time"/></div><Panel title="Upcoming payments" meta="August and September"><div className="bill-table">{bills.map(b=><article key={b.name}><span className="merchant-icon">{b.name[0]}</span><div className="bill-main"><b>{b.name}</b><small>{b.category} · Monthly</small></div><div><small>Due date</small><b>{b.due}</b></div><div><small>Amount</small><b>{formatCurrency(b.amount)}</b></div><span className={`status ${b.status.toLowerCase().replace(" ","-")}`}>{b.status}</span><button>···</button></article>)}</div></Panel></AppShell>}

function Reports(){return <AppShell title="Reports" subtitle="Understand the month behind the totals" action={<button className="primary-action" onClick={()=>window.print()}>↥ Print report</button>}><div className="report-tabs"><button className="active">Monthly summary</button><button>Income</button><button>Expenses</button><button>Budget</button><button>Investments</button></div><div className="summary-row three"><Stat label="Total income" value="Rs. 330,000" change="↑ 11.9% from July"/><Stat label="Total expenses" value="Rs. 164,800" change="↓ 11.9% from July"/><Stat label="Net cash flow" value="Rs. 165,200" change="50.1% savings rate"/></div><div className="dashboard-grid"><Panel title="Six-month cash flow" meta="March–August 2026" className="wide"><CashFlowChart data={monthly}/></Panel><Panel title="Expense distribution" meta="August 2026"><DonutChart items={budgets}/></Panel></div><Panel title="Monthly comparison" meta="Amounts in PKR"><div className="table-wrap"><table><thead><tr><th>Month</th><th>Income</th><th>Expenses</th><th>Net cash flow</th><th className="right">Savings rate</th></tr></thead><tbody>{monthly.map(m=><tr key={m.month}><td><b>{m.month} 2026</b></td><td>{formatCurrency(m.income)}</td><td>{formatCurrency(m.expense)}</td><td className="positive">+ {formatCurrency(m.income-m.expense)}</td><td className="right">{percent(m.income-m.expense,m.income)}%</td></tr>)}</tbody></table></div></Panel></AppShell>}

function Notifications(){const {notifications,setNotifications}=useFinance();return <AppShell title="Notifications" subtitle="Updates that need your attention"><div className="notification-page"><div className="notification-toolbar"><button className="active">All</button><button>Unread</button><button>Bills</button><button>Budgets</button><button onClick={()=>setNotifications(n=>n.map(x=>({...x,unread:false})))}>Mark all as read</button></div>{notifications.length?<div className="notification-list">{notifications.map(n=><article key={n.id} className={n.unread?"unread":""}><i/><div><b>{n.title}</b><p>{n.text}</p><small>{n.time}</small></div><button onClick={()=>setNotifications(x=>x.map(v=>v.id===n.id?{...v,unread:false}:v))}>···</button></article>)}</div>:<div className="empty-state"><span>♢</span><h2>You’re all caught up</h2><p>New bill, budget and account updates will appear here.</p></div>}</div></AppShell>}

function Settings(){const {theme,setTheme}=useFinance();const [saved,setSaved]=useState(false);return <AppShell title="Settings" subtitle="Profile and workspace preferences"><div className="settings-layout"><nav><button className="active">Profile</button><button>Appearance</button><button>Notifications</button><button>Financial preferences</button><button>Privacy</button><button>Security</button></nav><Panel title="Profile details" meta="Information shown in your workspace"><form className="settings-form" onSubmit={e=>{e.preventDefault();setSaved(true);setTimeout(()=>setSaved(false),2200)}}><div className="profile-edit"><span>MS</span><div><b>Muhammad Saad</b><small>muhammad.saad@example.com</small></div><button type="button">Change photo</button></div><div className="form-grid"><label>Full name<input defaultValue="Muhammad Saad"/></label><label>Occupation<input defaultValue="Product designer"/></label><label>Email<input type="email" defaultValue="muhammad.saad@example.com"/></label><label>Preferred currency<select><option>PKR — Pakistani Rupee</option></select></label></div><hr/><h3>Appearance</h3><div className="theme-choice"><button type="button" className={theme==="light"?"active":""} onClick={()=>setTheme("light")}><i>☀</i><span><b>Light</b><small>Bright and clear</small></span></button><button type="button" className={theme==="dark"?"active":""} onClick={()=>setTheme("dark")}><i>☾</i><span><b>Dark</b><small>Reduced glare</small></span></button></div><div className="form-actions"><span>{saved&&"Changes saved"}</span><button className="primary-action">Save changes</button></div></form></Panel></div></AppShell>}

function Modal({title,children,close}){return <div className="modal-layer" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><header><h2>{title}</h2><button onClick={close} aria-label="Close">×</button></header>{children}</div></div>}

function Login(){const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);function submit(e){e.preventDefault();setLoading(true);setTimeout(()=>window.location.href="/app",700)}return <main className="auth-page"><section className="auth-brand"><a className="brand" href="/"><span>h</span>Hisaab</a><div><p className="eyebrow">A clearer financial routine</p><h1>All the useful details, in one considered view.</h1><div className="auth-quote"><p>“I can check our bills, household budget and savings goals without opening three different sheets.”</p><span><b>Hira Siddiqui</b><small>Freelance art director, Lahore</small></span></div></div><small>Demo portfolio project · No live bank connections</small></section><section className="auth-form-wrap"><form onSubmit={submit}><a className="mobile-brand brand" href="/"><span>h</span>Hisaab</a><p className="eyebrow">Welcome back</p><h2>Sign in to view your finances</h2><p>Use the demo details below or enter any valid email and password.</p><label>Email address<input type="email" defaultValue="muhammad.saad@example.com" required/></label><label>Password<div className="password"><input type={show?"text":"password"} defaultValue="demo1234" minLength="6" required/><button type="button" onClick={()=>setShow(!show)}>{show?"Hide":"Show"}</button></div></label><div className="remember"><label><input type="checkbox" defaultChecked/> Remember me</label><button type="button">Forgot password?</button></div><button className="login-button" disabled={loading}>{loading?"Signing in…":"Sign in"}</button><p className="auth-switch">New to Hisaab? <button type="button">Create an account</button></p></form></section></main>}

function NotFound(){return <main className="not-found"><a className="brand" href="/"><span>h</span>Hisaab</a><div><b>404</b><h1>We couldn’t find that page.</h1><p>The link may be out of date, or the page may have moved.</p><a className="button" href="/app">Return to overview</a></div></main>}

function Router(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/app" element={<Dashboard/>}/><Route path="/app/transactions" element={<Transactions/>}/><Route path="/app/budgets" element={<Budgets/>}/><Route path="/app/investments" element={<Investments/>}/><Route path="/app/goals" element={<Goals/>}/><Route path="/app/bills" element={<Bills/>}/><Route path="/app/reports" element={<Reports/>}/><Route path="/app/notifications" element={<Notifications/>}/><Route path="/app/settings" element={<Settings/>}/><Route path="*" element={<NotFound/>}/></Routes>}
export default function FinanceApp(){return <FinanceProvider><BrowserRouter><Router/></BrowserRouter></FinanceProvider>}
